# Generated by Django 6.0.4 on 2026-04-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.IntegerField(help_text='ID de la URL oficial', unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('url_detalle', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonos', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_1', models.EmailField(blank=True, max_length=255, null=True)),
                ('mail_2', models.EmailField(blank=True, max_length=255, null=True)),
                ('sitio_web', models.URLField(blank=True, max_length=500, null=True)),
                ('vicaria', models.CharField(blank=True, max_length=100, null=True)),
                ('decanato', models.CharField(blank=True, max_length=100, null=True)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
                ('clero_cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('parroco', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_ereccion_canonica', models.CharField(blank=True, max_length=100, null=True)),
                ('comenzo_a_funcionar', models.CharField(blank=True, max_length=100, null=True)),
                ('limite_parroquial', models.TextField(blank=True, null=True)),
                ('detalles_completos', models.BooleanField(default=False)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parroquia',
                'verbose_name_plural': 'Parroquias',
            },
        ),
    ]
