# Generated by Django 6.0.4 on 2026-04-24 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parroquia',
            name='tiene_redes',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('otro', 'Otro')], max_length=50)),
                ('url', models.URLField(max_length=500)),
                ('activo', models.BooleanField(default=True)),
                ('verificado', models.BooleanField(default=False)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes', to='iglesias.parroquia')),
            ],
            options={
                'unique_together': {('parroquia', 'url')},
            },
        ),
    ]
