# Generated by Django 6.0.4 on 2026-05-12 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0002_parroquia_tiene_redes_redsocial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostParroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(help_text='ID nativo de Meta', max_length=100, unique=True)),
                ('red_social', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('imagen_url', models.URLField(help_text='Puede caducar en Instagram', max_length=1000)),
                ('procesado', models.BooleanField(default=False)),
                ('es_evento', models.BooleanField(help_text='null = sin procesar', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField(blank=True, help_text='Respuesta cruda de la API', null=True)),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_redes', to='iglesias.parroquia')),
            ],
            options={
                'verbose_name': 'Post de Parroquia',
                'verbose_name_plural': 'Posts de Parroquias',
                'ordering': ['-creado_en'],
            },
        ),
    ]
