# Generated by Django 6.0.4 on 2026-05-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0003_postparroquia'),
    ]

    operations = [
        migrations.AddField(
            model_name='postparroquia',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, help_text='Fecha de publicación en la red social', null=True),
        ),
    ]
