# Generated by Django 6.0.4 on 2026-05-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0005_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='verificado',
            field=models.BooleanField(default=False, help_text='Confirmado manualmente por un administrador'),
        ),
    ]
