# Generated by Django 6.0.4 on 2026-05-14 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0006_evento_verificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioMisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.CharField(max_length=100)),
                ('horarios', models.CharField(max_length=100)),
                ('nota', models.TextField(blank=True, null=True)),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_misa', to='iglesias.parroquia')),
            ],
            options={
                'verbose_name': 'Horario de Misa',
                'verbose_name_plural': 'Horarios de Misa',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InfoBaiglesias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_completa', models.TextField(blank=True, null=True)),
                ('como_llegar', models.TextField(blank=True, null=True)),
                ('url_scrapeada', models.URLField(max_length=500)),
                ('scrapeado_el', models.DateTimeField(auto_now=True)),
                ('parroquia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_bai', to='iglesias.parroquia')),
            ],
            options={
                'verbose_name': 'Info BAIglesias',
                'verbose_name_plural': 'Infos BAIglesias',
            },
        ),
    ]
