# Generated by Django 6.0.4 on 2026-05-18 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0007_horariomisa_infobaiglesias'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Evento',
                'verbose_name_plural': 'Categorías de Evento',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='audiencia',
            field=models.CharField(blank=True, choices=[('ambos', 'Hombres y Mujeres'), ('hombres', 'Hombres'), ('mujeres', 'Mujeres')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='capacidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='edad_desde',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='edad_hasta',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='exportado_sheets',
            field=models.BooleanField(default=False, help_text='True si fue exportado a Google Sheets'),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='gratuito',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='ubicacion_ciudad',
            field=models.CharField(blank=True, default='Buenos Aires', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='ubicacion_cp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='ubicacion_direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='ubicacion_lugar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='ubicacion_provincia',
            field=models.CharField(blank=True, default='Buenos Aires', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='url_externa',
            field=models.URLField(blank=True, help_text='Link de contacto o inscripción (WhatsApp, formulario, etc.)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='iglesias.categoriaevento'),
        ),
    ]
