# Generated by Django 6.0.4 on 2026-05-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0009_tipo_evento_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('corriendo', 'Corriendo'), ('completado', 'Completado'), ('error', 'Error')], default='corriendo', max_length=20)),
                ('total', models.IntegerField(default=0)),
                ('procesados', models.IntegerField(default=0)),
                ('posts_nuevos', models.IntegerField(default=0)),
                ('eventos_nuevos', models.IntegerField(default=0)),
                ('errores', models.IntegerField(default=0)),
                ('parroquia_actual', models.CharField(blank=True, max_length=255)),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('mensaje_final', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Scraper Job',
                'ordering': ['-iniciado_en'],
            },
        ),
    ]
