# Generated by Django 6.0.4 on 2026-05-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0010_scraperjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariomisa',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='horariomisa',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
