# Generated by Django 6.0.4 on 2026-05-26 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0011_horariomisa_actualizado_en_horariomisa_creado_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_usuario', models.TextField(help_text='Texto libre ingresado por el usuario')),
                ('propuesta_ia', models.JSONField(blank=True, help_text='Lista de dicts con dias/horarios propuestos por la IA', null=True)),
                ('resumen_cambios', models.TextField(blank=True, help_text='Descripción de los cambios detectados por la IA', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aplicado', 'Aplicado'), ('descartado', 'Descartado')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_horario', to='iglesias.parroquia')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Horario',
                'verbose_name_plural': 'Reportes de Horario',
                'ordering': ['-creado_en'],
            },
        ),
    ]
