# Generated by Django 6.0.4 on 2026-05-27 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0014_horariomisa_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidacionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones_horario', to='iglesias.parroquia')),
            ],
            options={
                'verbose_name': 'Validación de Horario',
                'verbose_name_plural': 'Validaciones de Horario',
                'ordering': ['-creado_en'],
            },
        ),
    ]
