# Generated by Django 6.0.4 on 2026-05-28 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0015_validacionhorario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportehorario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_horario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='validacionhorario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validaciones_horario_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('proveedor', models.CharField(blank=True, help_text='google, facebook, etc.', max_length=20, null=True)),
                ('score', models.IntegerField(default=0)),
                ('reportes_enviados', models.IntegerField(default=0)),
                ('reportes_aprobados', models.IntegerField(default=0)),
                ('reportes_rechazados', models.IntegerField(default=0)),
                ('validaciones_enviadas', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'ordering': ['-score'],
            },
        ),
    ]
