# Generated by Django 6.0.4 on 2026-05-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0016_reportehorario_usuario_validacionhorario_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parroquia',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parroquia',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
