# Generated by Django 6.0.4 on 2026-05-28 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0017_parroquia_latitud_parroquia_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='parroquia_favorita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_favoritos', to='iglesias.parroquia'),
        ),
    ]
