# Generated by Django 6.0.4 on 2026-05-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0018_perfilusuario_parroquia_favorita'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportehorario',
            name='fuente',
            field=models.CharField(choices=[('usuario', 'Reporte de usuario'), ('scraper', 'Scraper automático')], default='usuario', max_length=20),
        ),
        migrations.AddField(
            model_name='reportehorario',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL de la imagen del post scrapeado', max_length=1000, null=True),
        ),
    ]
