# Generated by Django 6.0.4 on 2026-05-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0019_reportehorario_fuente_reportehorario_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportehorario',
            name='url_post',
            field=models.URLField(blank=True, help_text='URL del post original en la red social', max_length=1000, null=True),
        ),
    ]
