# Generated by Django 6.0.4 on 2026-05-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0020_reportehorario_url_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen del banner (recomendado: 728x90px)', null=True, upload_to='banners/')),
                ('url_destino', models.URLField(blank=True, help_text='URL a la que redirige el banner', max_length=500, null=True)),
                ('texto_alternativo', models.CharField(blank=True, help_text='Texto alternativo para SEO y accesibilidad', max_length=200)),
                ('posicion', models.CharField(choices=[('resultados', 'Entre resultados del buscador'), ('detalle', 'Página de detalle de parroquia')], default='resultados', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner publicitario',
                'verbose_name_plural': 'Banners publicitarios',
                'ordering': ['orden', '-creado_en'],
            },
        ),
    ]
