# Generated by Django 6.0.4 on 2026-05-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0021_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='imagen_static',
            field=models.CharField(blank=True, help_text='Ruta estática ej: iglesias/img/ad_gaudium1.jpeg', max_length=200, null=True),
        ),
    ]
