# Generated by Django 6.0.4 on 2026-05-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0022_banner_imagen_static'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperjob',
            name='origen',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático')], default='manual', max_length=20),
        ),
    ]
