# Generated by Django 6.0.4 on 2026-06-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0023_scraperjob_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='parroquia',
            name='horarios_verificados',
            field=models.BooleanField(default=False, help_text='Si True, el scraper no sobreescribe horarios de misa'),
        ),
        migrations.AddField(
            model_name='parroquia',
            name='redes_verificadas',
            field=models.BooleanField(default=False, help_text='Si True, el scraper no agrega ni modifica redes sociales'),
        ),
        migrations.AddField(
            model_name='parroquia',
            name='web_verificada',
            field=models.BooleanField(default=False, help_text='Si True, el scraper no sobreescribe sitio_web'),
        ),
    ]
