# Generated by Django 6.0.4 on 2026-06-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0024_parroquia_horarios_verificados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parroquia',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad o localidad', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parroquia',
            name='diocesis',
            field=models.CharField(blank=True, help_text='Diócesis o Arquidiócesis', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='parroquia',
            name='provincia',
            field=models.CharField(blank=True, default='Ciudad Autónoma de Buenos Aires', help_text='Provincia donde se encuentra la parroquia', max_length=100, null=True),
        ),
    ]
