# Generated by Django 6.0.4 on 2026-06-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0027_comentarioparroquia_votohorario'),
    ]

    operations = [
        migrations.AddField(
            model_name='parroquia',
            name='imagen_url',
            field=models.URLField(blank=True, default='', help_text='URL de imagen de la fachada o interior. Obtenida por scraping.', max_length=500),
        ),
    ]
