# Generated by Django 6.0.4 on 2026-06-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0028_add_imagen_url_to_parroquia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parroquia',
            name='imagen_url',
            field=models.URLField(blank=True, default='', help_text='URL de imagen de la fachada o interior. Obtenida por scraping.', max_length=2000),
        ),
    ]
