# Generated by Django 6.0.4 on 2026-06-06 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0029_increase_imagen_url_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioPropuestoAgregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('horarios_json', models.JSONField(default=list)),
                ('confianza', models.FloatField(default=0.0)),
                ('total_aportes', models.IntegerField(default=0)),
                ('aportes_con_historial', models.IntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_propuestos', to='iglesias.parroquia')),
            ],
            options={
                'verbose_name': 'Horario propuesto agregado',
                'verbose_name_plural': 'Horarios propuestos agregados',
                'ordering': ['dia_semana'],
                'unique_together': {('parroquia', 'dia_semana')},
            },
        ),
    ]
