# Generated by Django 6.0.4 on 2026-06-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0030_horario_propuesto_agregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarioparroquia',
            name='estado_moderacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='comentarioparroquia',
            name='moderado_por_ia',
            field=models.BooleanField(default=False, help_text='True si la IA ya procesó este comentario'),
        ),
        migrations.AddField(
            model_name='comentarioparroquia',
            name='razon_rechazo',
            field=models.CharField(blank=True, help_text='Razón del rechazo (filtro local o IA)', max_length=255, null=True),
        ),
    ]
