# Generated by Django 6.0.4 on 2026-06-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0031_comentarioparroquia_estado_moderacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarioparroquia',
            name='apelado',
            field=models.BooleanField(default=False, help_text='El usuario marcó este rechazo como error'),
        ),
        migrations.AddField(
            model_name='comentarioparroquia',
            name='apelado_en',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el usuario apeló', null=True),
        ),
    ]
