# Generated by Django 6.0.4 on 2026-06-08 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0032_comentarioparroquia_apelado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuscripcionAvisoMisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_semana', models.JSONField(default=list, help_text='Lista de días [0-6] donde 0=Lunes. Vacío = todos los días.')),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones_avisos', to='iglesias.parroquia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones_avisos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripción aviso misa',
                'verbose_name_plural': 'Suscripciones avisos misa',
                'unique_together': {('usuario', 'parroquia')},
            },
        ),
    ]
