# Generated by Django 6.0.4 on 2026-06-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0035_votohorario_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='parroquia_favorita',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='parroquias_favoritas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_favoritos', to='iglesias.parroquia'),
        ),
    ]
