# Generated by Django 6.0.4 on 2026-06-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0036_remove_perfilusuario_parroquia_favorita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
