# Generated by Django 6.0.4 on 2026-06-11 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0037_add_avatar_to_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='avatar',
        ),
    ]
