# Generated by Django 6.0.4 on 2026-06-25 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0038_remove_avatar_imagefield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parroquia',
            name='gestionado_por_parroquia',
            field=models.BooleanField(default=False, help_text='Si True, los datos del gestor tienen prioridad; el scraper no sobreescribe campos clave'),
        ),
        migrations.AddField(
            model_name='parroquia',
            name='imagen_principal',
            field=models.URLField(blank=True, help_text='URL de imagen subida vía ImageKit por el gestor de la parroquia', max_length=1000),
        ),
        migrations.AddField(
            model_name='postparroquia',
            name='descripcion_evento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='postparroquia',
            name='fecha_evento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postparroquia',
            name='hora_evento',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postparroquia',
            name='titulo_evento',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='postparroquia',
            name='imagen_url',
            field=models.URLField(blank=True, default='', help_text='Puede caducar en Instagram', max_length=1000),
        ),
        migrations.AlterField(
            model_name='postparroquia',
            name='red_social',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('gestor', 'Gestor de Parroquia')], max_length=20),
        ),
        migrations.CreateModel(
            name='PerfilGestorParroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('parroquia', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gestor', to='iglesias.parroquia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gestor_parroquia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Gestor de Parroquia',
                'verbose_name_plural': 'Perfiles de Gestores de Parroquia',
            },
        ),
    ]
