# Generated by Django 6.0.4 on 2026-08-10 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0039_panel_gestor_parroquia'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('tipo', models.CharField(choices=[('vista_home', 'Vista de portada'), ('busqueda', 'Búsqueda'), ('vista_parroquia', 'Vista de parroquia'), ('click_web', 'Click en sitio web'), ('click_telefono', 'Click en teléfono'), ('click_whatsapp', 'Click en WhatsApp'), ('click_email', 'Click en email'), ('click_red_social', 'Click en red social'), ('click_como_llegar', 'Click en cómo llegar'), ('banner_impresion', 'Impresión de banner'), ('banner_click', 'Click en banner')], db_index=True, max_length=30)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='iglesias.banner')),
                ('parroquia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='iglesias.parroquia')),
            ],
            options={
                'verbose_name': 'Métrica diaria',
                'verbose_name_plural': 'Métricas diarias',
                'indexes': [models.Index(fields=['fecha', 'tipo'], name='iglesias_me_fecha_8ff0c9_idx')],
            },
        ),
    ]
